spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_pablo?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect # vai conversar com o banco com esse dialeto
    show_sql: false # true qnd tiver debugando
    open-in-view: false